version: 2
updates:
  # Keep all NuGet dependencies up to date across the solution
  - package-ecosystem: "nuget"
    directory: "/" # Scan the whole repo for .csproj and NuGet manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Stockholm"
    target-branch: "main"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    groups:
      minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"

  # Keep GitHub Actions used in workflows up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "Europe/Stockholm"
    target-branch: "main"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
